In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.3.5


In [5]:
array=[1,2,3]*2

In [3]:
array=np.array([1,2,3])*2

In [6]:
print(array)

[1, 2, 3, 1, 2, 3]


In [43]:
# 4x5 pizza grid: toppings coded as numbers (1=cheese, 2=pepperoni, 3=mushroom, 4=olive)
pizza = np.array([
    [1, 2, 3, 4, 1],  # Slice 0
    [2, 3, 1, 2, 3],  # Slice 1
    [4, 1, 2, 3, 4],  # Slice 2
    [3, 4, 1, 2, 1]   # Slice 3
])

In [8]:
print("Full Pizza:\n", pizza)

Full Pizza:
 [[1 2 3 4 1]
 [2 3 1 2 3]
 [4 1 2 3 4]
 [3 4 1 2 1]]


In [10]:
# Challenge 1: Serve First Two Slices
print(pizza[0:2])
print(pizza[:2,:])

[[1 2 3 4 1]
 [2 3 1 2 3]]
[[1 2 3 4 1]
 [2 3 1 2 3]]


In [19]:
#  Cheese-Only Toppings (Column 0)
print(pizza[:, 0])

[1 2 4 3]


In [66]:
# Challenge 3: Pepperoni Middles with Step
# Extract every other topping starting from column 1, but only from middle slices (rows 1:3).
print(pizza[1:3,1::2])

[[3 2]
 [1 3]]


In [69]:
#Challenge 4: Reverse a Slice
# Serve slice 2 backwards (reverse columns). 
 
print(pizza[2:3,::-1])

[[4 3 2 1 4]]


In [ ]:
# 1. Pizza Chef Simulator (your current theme!)

In [70]:
pizza = np.array([
    ["🧀","🍕","🍄","🫒","🧀"],
    ["🍕","🍄","🧀","🍕","🍄"],
    ["🫒","🧀","🍕","🍄","🫒"],
    ["🍄","🫒","🧀","🍕","🧀"]
])


In [83]:
# Slice out the right half of the pizza.
print(pizza[:,2:])

[['🍄' '🫒' '🧀']
 ['🧀' '🍕' '🍄']
 ['🍕' '🍄' '🫒']
 ['🧀' '🍕' '🧀']]


In [84]:
# Slice out every other topping in each row.
print(pizza[:,::2])

[['🧀' '🍄' '🧀']
 ['🍕' '🧀' '🍄']
 ['🫒' '🍕' '🫒']
 ['🍄' '🧀' '🧀']]


In [87]:
# Get the crust (first + last row).
print(pizza[::3])

[['🧀' '🍕' '🍄' '🫒' '🧀']
 ['🍄' '🫒' '🧀' '🍕' '🧀']]


In [89]:
# Extract a 2×2 “topping sample” somewhere in the middle.
print(pizza[1:3,1:3:1])

[['🍄' '🧀']
 ['🧀' '🍕']]


In [90]:
# 2. Emoji Art Decoder
art = np.array([
    ["⭐","⭐","⭐","⭐","⭐"],
    ["⭐","❤️","❤️","❤️","⭐"],
    ["⭐","❤️","⭐","❤️","⭐"],
    ["⭐","❤️","❤️","❤️","⭐"],
    ["⭐","⭐","⭐","⭐","⭐"]
])


In [93]:
# Slice out the heart square.
print(art[1:4,1:4])

[['❤️' '❤️' '❤️']
 ['❤️' '⭐' '❤️']
 ['❤️' '❤️' '❤️']]


In [132]:
# Slice only the border (outer frame).
print(art[::4,::4])
copy=art.copy()
copy[1:-1,1:-1]=""
copy

[['⭐' '⭐']
 ['⭐' '⭐']]


array([['⭐', '⭐', '⭐', '⭐', '⭐'],
       ['⭐', '', '', '', '⭐'],
       ['⭐', '', '', '', '⭐'],
       ['⭐', '', '', '', '⭐'],
       ['⭐', '⭐', '⭐', '⭐', '⭐']], dtype='<U2')

In [133]:
art[::2, ::2]


array([['⭐', '⭐', '⭐'],
       ['⭐', '⭐', '⭐'],
       ['⭐', '⭐', '⭐']], dtype='<U2')